
export const users =[
    {
      id: 1,
      role: 'admin',
      displayRole: 'ADMIN',
      name: 'KOWSER ALAM',
        email: 'admin@gmail.com',
        password: '1234'
    },
    {
        id: 2,
        role: 'security',
        displayRole: 'SECURITY & ADMINISTRATION',
        name: 'MD S ALAM',
        email: 'security@gmail.com',
        password: '1234'
    },
    {
        id: 3,
        role: 'checker',
        displayRole: 'CHECK-IN',
        name: 'ZAKIR HOSSAIN',
        email: 'checkin@gmail.com',
        password: '1234'
    },
    {
        id: 4,
        role: 'storage',
        displayRole: 'STORAGE',
        name: 'AMINUL AHMED',
        email: 'storage@gmail.com',
        password: '1234'
    },
]
export let CarList = [
  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Corporate Customer",
    "customerAddress": "Corporate Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6760",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg",
   
  },  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Corporate Customer",
    "customerAddress": "Corporate Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6761",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Corporate Customer",
    "customerAddress": "Corporate Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6762",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },
  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Corporate Customer",
    "customerAddress": "Corporate Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6763",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Corporate Customer",
    "customerAddress": "Corporate Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6764",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  }

]
export let vehicleList = [
  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Demo Customer",
    "customerAddress": "Demo Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6755",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Demo Customer",
    "customerAddress": "Demo Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6756",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Demo Customer",
    "customerAddress": "Demo Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6757",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },
  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Demo Customer",
    "customerAddress": "Demo Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6758",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  },  {
    "sn":"01",
    "sl": "#SL-0000001-23",
    "Customer": "Demo Customer",
    "customerAddress": "Demo Street, Cityville, CA 12345",
    "queueNo": "01",
    "queueStockStatus": "Active",
    "queueStatus": "Parking",
    "vehicleNumber": "DHA-MET-6759",
    "date": "23-October-23",
    "vehicleMaximumWeight": "2000 kg"
  }

]
export let parkingList = [
    {
      "sn":"01",
      "sl": "#SL-0000001-23",
      "salesOrderNumber": "#SO-MN-0001",
      "Customer": "John Doe",
      "customerAddress": "123 Main Street, Cityville, CA 12345",
      "deliveryAddress": "456 Elm Avenue, Townsville, CA 54321",
      "Product": "Product-1",
      "Quantity": 100,
      "stockLocation": "Packer-1",
      "queueNo": "01",
      "queueStockStatus": "Active",
      "queueStatus": "Cleared",
      "vehicleNumber": "DHA-MET-6754",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 12:21 PM",
      "vehicleMaximumWeight": "2000 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"20.94 min",
    },
    {
      "sn":"01",
      "sl": "#SL-0000002-23",
      "salesOrderNumber": "#SO-MN-0002",
      "Customer": "Jane Smith",
      "customerAddress": "789 Elm Road, Villagetown, NY 67890",
      "deliveryAddress": "321 Oak Lane, Hamletville, NY 45678",
      "Product": "Gadget Y",
      "Quantity": 75,
      "stockLocation": "Packer-3",
      "queueNo": "02",
      "queueStockStatus": "Active",
      "queueStatus": "Cleared",
      "vehicleNumber": "CHA-MET-2309",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 10:21 P.M",
      "vehicleMaximumWeight": "2500 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"20.94 min",
    },
    {
      "sl": "#SL-0000003-23",
      "salesOrderNumber": "#SO-MN-0003",
      "Customer": "Robert Johnson",
      "customerAddress": "456 Pine Avenue, Forestville, TX 34567",
      "deliveryAddress": "987 Birch Street, Lakeside, TX 89012",
      "Product": "Thingamajig Z",
      "Quantity": 50,
      "stockLocation": "Warehouse-1",
      "queueNo": "03",
      "queueStockStatus": "Active",
      "queueStatus": "Cleared",
      "vehicleNumber": "DHA-MET-1234",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 09:21 PM",
      "vehicleMaximumWeight": "1800 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"20.94 min",
    },
    {
      "sl": "#SL-0000004-23",
      "salesOrderNumber": "#SO-MN-0004",
      "Customer": "Susan Lee",
      "customerAddress": "567 Maple Drive, Riverside, FL 23456",
      "deliveryAddress": "123 Cedar Road, Lakeside, FL 56789",
      "Product": "Doodad W",
      "Quantity": 30,
      "stockLocation": "Packer-1",
      "queueNo": "04",
      "queueStockStatus": "Active",
      "queueStatus": "In Queue",
      "vehicleNumber": "CHA-MET-5678",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 05:21 AM",
      "vehicleMaximumWeight": "2200 kg",
      "LoadingStatus":"Pending",
      "LoadingTime":"00.00 min",
    },
    {
      "sl": "#SL-0000005-23",
      "salesOrderNumber": "#SO-MN-0005",
      "Customer": "Michael Wilson",
      "customerAddress": "789 Oak Street, Hillside, CA 45678",
      "deliveryAddress": "234 Pine Lane, Riverside, CA 78901",
      "Product": "Whatchamacallit V",
      "Quantity": 90,
      "stockLocation": "Packer-3",
      "queueNo": "05",
      "queueStockStatus": "Active",
      "queueStatus": "In Queue",
      "vehicleNumber": "DHA-MET-9876",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 03:21 PM",
      "vehicleMaximumWeight": "2800 kg",
      "LoadingStatus":"Pending",
      "LoadingTime":"00.00 min",
    },
    {
      "sl": "#SL-0000006-23",
      "salesOrderNumber": "#SO-MN-0006",
      "Customer": "Laura Davis",
      "customerAddress": "123 Elm Road, Mountainville, TX 12345",
      "deliveryAddress": "456 Oak Lane, Hillside, TX 54321",
      "Product": "Contraption U",
      "Quantity": 70,
      "stockLocation": "Warehouse-2",
      "queueNo": "06",
      "queueStockStatus": "Deactive",
      "queueStatus": "Cleared",
      "vehicleNumber": "CHA-MET-4321",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 04:21 PM",
      "vehicleMaximumWeight": "2600 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"20.94 min",
    },
    {
      "sl": "#SL-0000007-23",
      "salesOrderNumber": "#SO-MN-0007",
      "Customer": "Daniel Brown",
      "customerAddress": "456 Cedar Lane, Riverside, NY 45678",
      "deliveryAddress": "789 Pine Avenue, Lakeside, NY 78901",
      "Product": "Doohickey T",
      "Quantity": 40,
      "stockLocation": "Packer-1",
      "queueNo": "07",
      "queueStockStatus": "Active",
      "queueStatus": "Cleared",
      "vehicleNumber": "DHA-MET-5678",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 03:21 PM",
      "vehicleMaximumWeight": "2300 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"20.94 min",
    },
    {
      "sl": "#SL-0000008-23",
      "salesOrderNumber": "#SO-MN-0008",
      "Customer": "Emily Green",
      "customerAddress": "234 Birch Drive, Mountainville, CA 23456",
      "deliveryAddress": "567 Oak Road, Hillside, CA 56789",
      "Product": "Dinglehopper S",
      "Quantity": 60,
      "stockLocation": "Packer-3",
      "queueNo": "08",
      "queueStockStatus": "Active",
      "queueStatus": "Cleared",
      "vehicleNumber": "CHA-MET-7890",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 12:21 PM",
      "vehicleMaximumWeight": "2100 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"20.94 min",
    },
    {
      "sl": "#SL-0000009-23",
      "salesOrderNumber": "#SO-MN-0009",
      "Customer": "Jacob Parker",
      "customerAddress": "987 Pine Street, Lakeside, FL 98765",
      "deliveryAddress": "123 Maple Lane, Riverside, FL 12345",
      "Product": "Sprocket R",
      "Quantity": 35,
      "stockLocation": "Parking",
      "queueNo": "09",
      "queueStockStatus": "Active",
      "queueStatus": "In Queue",
      "vehicleNumber": "DHA-MET-2468",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 08:21 PM",
      "vehicleMaximumWeight": "2400 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"10.94 min",
    },
    
    {
      "sl": "#SL-0000009-28",
      "salesOrderNumber": "#SO-MN-0091",
      "Customer": "Jacob Parker",
      "customerAddress": "987 Pine Street, Lakeside, FL 98765",
      "deliveryAddress": "123 Maple Lane, Riverside, FL 12345",
      "Product": "Sprocket R",
      "Quantity": 35,
      "stockLocation": "Parking",
      "queueNo": "09",
      "queueStockStatus": "Active",
      "queueStatus": "In Queue",
      "vehicleNumber": "DHA-MET-2488",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 08:21 PM",
      "vehicleMaximumWeight": "2400 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"10.94 min",
    },
    {
      "sl": "#SL-0000010-23",
      "salesOrderNumber": "#SO-MN-0010",
      "Customer": "Olivia Taylor",
      "customerAddress": "456 Cedar Road, Hillside, TX 45678",
      "deliveryAddress": "789 Elm Avenue, Lakeside, TX 78901",
      "Product": "Thingamajig Q",
      "Quantity": 45,
      "stockLocation": "Packer-2",
      "queueNo": "10",
      "queueStockStatus": "Dective",
      "queueStatus": "Cleared",
      "vehicleNumber": "CHA-MET-5432",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 04:10 PM",
      "vehicleMaximumWeight": "2700 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"16.94 min",
    },{
      "sl": "#SL-0000001-23",
      "salesOrderNumber": "#SO-MN-0002",
      "Customer": "John Doe",
      "customerAddress": "123 Main Street, Cityville, CA 12345",
      "deliveryAddress": "105 Elm Avenue, Townsville, CA 54321",
      "Product": "Product-2",
      "Quantity": 40,
      "stockLocation": "Packer-1",
      "queueNo": "01",
      "queueStockStatus": "Active",
      "queueStatus": "Cleared",
      "vehicleNumber": "DHA-MET-6754",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 12:30 PM",
      "vehicleMaximumWeight": "2000 kg",
      "LoadingStatus":"Completed",
      "LoadingTime":"18.00 min",
    },{
      "sl": "#SL-0000001-23",
      "salesOrderNumber": "#SO-MN-0003",
      "Customer": "John Doe",
      "customerAddress": "123 Main Street, Cityville, CA 12345",
      "deliveryAddress": "350 Elm Avenue, Townsville, CA 54321",
      "Product": "Product-3",
      "Quantity": 50,
      "stockLocation": "Packer-3",
      "queueNo": "01",
      "queueStockStatus": "Active",
      "queueStatus": "In Queue",
      "vehicleNumber": "DHA-MET-6754",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 12:45 PM",
      "vehicleMaximumWeight": "2000 kg",
      "LoadingStatus":"Pending",
      "LoadingTime":"00.00 min",
    },{
      "sl": "#SL-0000001-23",
      "salesOrderNumber": "#SO-MN-0001",
      "Customer": "John Doe",
      "customerAddress": "123 Main Street, Cityville, CA 12345",
      "deliveryAddress": "874 Elm Avenue, Townsville, CA 54321",
      "Product": "Product-4",
      "Quantity": 60,
      "stockLocation": "Warehouse-1",
      "queueNo": "01",
      "queueStockStatus": "Active",
      "queueStatus": "In Queue",
      "vehicleNumber": "DHA-MET-6754",
      "entryTime": "10:30 A.M",
      "exitTime": "03:45 P.M",
      "date": "23-October-23 12:56 PM",
      "vehicleMaximumWeight": "2000 kg",
      "LoadingStatus":"Pending",
      "LoadingTime":"00.00 min",
    },
  ]

// export let parkingList = [
//     { 
//         id: 1,
//         carMake: "Toyota",
//         carModel: "Camry",
//         licensePlate: "ABC-123",
//         isOccupied: true,
//         entryTime: "2023-10-23 10:30:00",
//         exitTime: "2023-10-23 16:45:00",
//         entryUserId: 1
//     },
//     { 
//         id: 2,
//         carMake: "Honda",
//         carModel: "Civic",
//         licensePlate: "XYZ-789",
//         isOccupied: true,
//         entryTime: "2023-10-23 09:15:00",
//         exitTime: "2023-10-23 17:20:00",
//         entryUserId: 2
//     },
//     { 
//         id: 3,
//         carMake: "Ford",
//         carModel: "F-150",
//         licensePlate: "LMN-456",
//         isOccupied: false,
//         entryTime: null,
//         exitTime: null,
//         entryUserId: 1
//     },
    
//     { 
//         id: 4,
//         carMake: "Honda",
//         carModel: "Civic",
//         licensePlate: "XYZ-789",
//         isOccupied: true,
//         entryTime: "2023-10-24 09:15:00",
//         exitTime: "2023-10-24 17:20:00",
//         entryUserId: 2
//     }, { 
//         id: 5,
//         carMake: "Honda",
//         carModel: "Civic",
//         licensePlate: "XYZ-789",
//         isOccupied: true,
//         entryTime: "2023-10-25 09:15:00",
//         exitTime: "2023-10-25 17:20:00",
//         entryUserId: 2
//     }, { 
//         id: 6,
//         carMake: "Honda",
//         carModel: "Civic",
//         licensePlate: "XYZ-789",
//         isOccupied: true,
//         entryTime: "2023-10-27 09:15:00",
//         exitTime: "2023-10-29 24:20:00",
//         entryUserId: 2
//     },
// ];